version: '3'

services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
      

    ports:
      - "80:80"

    networks:
      - nginx_network



networks:
  nginx_network:
    external: true
