version: '3'

services:

  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
          - 8081:8081
   
 

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
      

    ports:
      - "80:80"

    networks:
      - nginx_network



networks:
  nginx_network:
    external: true
