version: '3'

services:
  sample-python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/sample-python

    restart: always
    ports:
      - "8000:8000"
    networks:
      - sample-python_network
      - nginx_network
    depends_on:
      - nginx_network

networks:
  sample-python_network:
    external: true
  nginx_network:
    external: true
